// Generated by CoffeeScript 1.8.0
(function() {
  window.jsevent = window.jsevent || {};

  window.jsevent.event = function(eventName, parameters) {
    var event;
    event = jQuery.Event(eventName, parameters);
    return jQuery(document).trigger(event);
  };

}).call(this);
